version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: node-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=production
    networks:
      - app-network
    # Healthcheck
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Client Service
  client:
    build:
      context: ./client
    container_name: react-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge